auto_open_output_folder: true
default_output_dir: ./torrents
default_upload_root: /mnt/user/data/downloads/torrents/qbittorrent/seedvault/
qbittorrent:
  auto_add_after_creation: true
  auto_torrent_management: true
  category: upload.audiobooks
  
  # Connection settings with production best practices
  connection_timeout: 10.0    # Connect timeout (seconds)
  read_timeout: 30.0         # Read timeout (seconds)
  pool_connections: 10       # HTTP connection pool size
  pool_maxsize: 10          # HTTP connection pool max size
  
  # Docker path mapping for container environments
  docker_path_mapping:
    /mnt/user/data: /data
  
  # qBittorrent server details
  host: 10.1.60.2
  port: 8083
  use_https: false
  base_path: ""             # For reverse proxy setups
  verify_tls: true
  
  # Authentication (using credential manager)
  password: ${QBIT_PASSWORD}
  username: ${QBIT_USERNAME}
  
  # Torrent management settings
  max_tag_length: 50
  save_path: /data/downloads/torrents/qbittorrent/seedvault/audiobooks
  tags:
  - Uploaded:H2OKing
  trackers:
  - ${TRACKER}

remember_last_folder: true
torrent_creation:
  comment: Created with Easy Torrent Creator
  format: v1
  optimize_alignment: true
  padded_file_size_limit: null
  piece_size: null
  poll_interval: 1.0
  private: true
  start_seeding: true
  timeout: 300
web_server:
  host: 0.0.0.0
  port: 8094
  reload: true
